[[https://github.com/appgate/sdp-operator/actions/workflows/docker.yml][https://github.com/appgate/sdp-operator/actions/workflows/docker.yml/badge.svg?branch=main&event=push]]
* appgate-operator
** Description
This project implements a kubernetes operator to configure an appgate system.

The main goal of the operator is to keep in sync the state of an appgate system
with an external state defined somewhere (github repository for instance).

The definition of the expected state is done in a declarative way (using yaml
files) where the desired entities are defined.

The operator then reacts to changes in those entities performing the required
operations to keep the appgate environment synchronized with the desired state.

The appgate operator supports the following API versions:

 - v12 (Appgate version 5.1)
 - v13 (Appgate version 5.2)
 - v14 (Appgate version 5.3)
 - v15 (Appgate version 5.4)
 - v16 (Appgate version 5.5)

The entities supported by the operator are:

   - Policy
   - Condition
   - Entitlement
   - RingfenceRule
   - Appliance
   - Site
   - IpPool
   - IdentityProvider
   - LocalUser
   - AdministrativeRole
   - MfaProvider
   - AdminMfaSettings
   - TrustedCertificate
   - CriteriaScripts
   - DeviceScript
   - EntitlementScript
   - ApplianceCustomization
   - GlobalSettings
   - ClientConnection

** How it works
Appgate entities are defined in terms of [[https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/][CRD]] in the k8s cluster so they can be
managed (created, deleted or modified) using `kubectl` command with yaml files
representing those CRD. (see the directory `examples`).

The appgate-operator, when running, will listen for changes on those CRD entities,
note that the operator listen to events inside a namespace.

When the operator starts, it gets the actual state from the appgate controller
and from there it starts listening for events.

On each event received it restores a timer, once the timer timeouts (meaning
that no more events were received in that specified time frame) the operator
will proceed to compute and apply a new `Plan`.

A `Plan` is the difference between the current state and the desired state and
it defines for each entity 4 subset of operations to perform:

 - create :: a new entity needs to be created
 - delete :: an existing entity needs to be deleted
 - modify :: an existing entity needs to be modified
 - share :: an entity that won't change

All the entities are identified by name, that way we don't need to save real
uuids in the configuration. Entities referencing other entities (entitlements
reference conditions for instance) do it by name also, the operator resolves
those names into real uuids before doing the queries.

*** Errors
There are different sources of errors.

Some entities reference another ones like `entitlements` using `conditions`. If
one entity references another entity that is not in the expeted state after the
`Plan` is applied then it's marked as a conflict error. If a plan contains
errors it won't be applied.

Another kind of error is when applying the plan for real. If the REST call to
the operator fails, that entity is marked as failed as well. Then later when
creating the new state those entity that failed will be removed from the new
state (or added if the operation was `delete`).

*** Modes of operation
**** DRY_MODE
When this flag is on the operator will compute the plan to apply but it won't do
any call.

**** CLEANUP_ON_STARTUP
When this flag is on the operator when initializing the state for first time
will remove all the entities that are not part of the set of builtin tags (see
[[*Configuration][configuration section]] to know how to configure this set).

***** Example 1
We have an appgate system with a condition but we dont have any condition
defined in kubernetes.

#+BEGIN_EXAMPLE
  2020-07-17 17:14:38,940 [INFO] [policies/appgate-test-1] Loop for policies/appgate-test-1 started
  2020-07-17 17:14:38,942 [INFO] [entitlements/appgate-test-1] Loop for entitlements/appgate-test-1 started
  2020-07-17 17:14:38,943 [INFO] [conditions/appgate-test-1] Loop for conditions/appgate-test-1 started
  2020-07-17 17:14:38,945 [INFO] [appgate-operator/appgate-test-1] Getting current state from controller
  2020-07-17 17:14:39,228 [INFO] [appgate-operator/appgate-test-1] Ready to get new events and compute a new plan
  2020-07-17 17:14:44,235 [INFO] [appgate-operator/appgate-test-1] No more events for a while, creating a plan
  2020-07-17 17:14:44,235 [WARNING] [appgate-operator/appgate-test-1] Running in dry-mode, nothing will be created
  2020-07-17 17:14:44,236 [INFO] [appgate-operator/appgate-test-1] AppgatePlan Summary:
  2020-07-17 17:14:44,236 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Condition'> Always [ee7b7e6f-e904-4b4f-a5ec-b3bef040643e]
  2020-07-17 17:14:44,236 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Condition'> my-new-condition [1bd1f4a8-d2ca-409d-b925-3530447caf45]
  2020-07-17 17:14:44,236 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Policy'> Builtin Administrator Policy [172143a0-7ed4-11e4-b4a9-0800200c9a66]
  2020-07-17 17:14:49,242 [INFO] [appgate-operator/appgate-test-1] No more events for a while, creating a plan
  2020-07-17 17:14:49,243 [WARNING] [appgate-operator/appgate-test-1] Running in dry-mode, nothing will be created
  2020-07-17 17:14:49,243 [INFO] [appgate-operator/appgate-test-1] AppgatePlan Summary:
  2020-07-17 17:14:49,244 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Condition'> Always [ee7b7e6f-e904-4b4f-a5ec-b3bef040643e]
  2020-07-17 17:14:49,244 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Condition'> my-new-condition [1bd1f4a8-d2ca-409d-b925-3530447caf45]
  2020-07-17 17:14:49,244 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Policy'> Builtin Administrator Policy [172143a0-7ed4-11e4-b4a9-0800200c9a66]
#+END_EXAMPLE

As we can see in this example the new condition (not built-in) is detected when
discovering the first state. Because we did not choose to cleanup on startup,
the condition is kept there and not managed by the operator.

***** Example 2
Same example when cleanup is on.

#+BEGIN_EXAMPLE
  2020-07-17 17:20:12,999 [INFO] [policies/appgate-test-1] Loop for policies/appgate-test-1 started
  2020-07-17 17:20:13,001 [INFO] [entitlements/appgate-test-1] Loop for entitlements/appgate-test-1 started
  2020-07-17 17:20:13,002 [INFO] [conditions/appgate-test-1] Loop for conditions/appgate-test-1 started
  2020-07-17 17:20:13,005 [INFO] [appgate-operator/appgate-test-1] Getting current state from controller
  2020-07-17 17:20:13,412 [INFO] [appgate-operator/appgate-test-1] Ready to get new events and compute a new plan
  2020-07-17 17:20:18,419 [INFO] [appgate-operator/appgate-test-1] No more events for a while, creating a plan
  2020-07-17 17:20:18,419 [WARNING] [appgate-operator/appgate-test-1] Running in dry-mode, nothing will be created
  2020-07-17 17:20:18,419 [INFO] [appgate-operator/appgate-test-1] AppgatePlan Summary:
  2020-07-17 17:20:18,420 [INFO] [appgate-operator/appgate-test-1] - <class 'appgate.types.Condition'> my-new-condition [1bd1f4a8-d2ca-409d-b925-3530447caf45]
  2020-07-17 17:20:18,420 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Condition'> Always [ee7b7e6f-e904-4b4f-a5ec-b3bef040643e]
  2020-07-17 17:20:18,420 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Policy'> Builtin Administrator Policy [172143a0-7ed4-11e4-b4a9-0800200c9a66]
#+END_EXAMPLE

Now we can see that the condition was marked as a deletion because it's not defined in the cluster.

If we have the cleanup option on BUT the cluster knows about those entities they are not deleted:

#+BEGIN_EXAMPLE
  2020-07-17 17:22:38,393 [INFO] [policies/appgate-test-1] Loop for policies/appgate-test-1 started
  2020-07-17 17:22:38,396 [INFO] [entitlements/appgate-test-1] Loop for entitlements/appgate-test-1 started
  2020-07-17 17:22:38,398 [INFO] [conditions/appgate-test-1] Loop for conditions/appgate-test-1 started
  2020-07-17 17:22:38,403 [INFO] [appgate-operator/appgate-test-1] Getting current state from controller
  2020-07-17 17:22:38,707 [INFO] [appgate-operator/appgate-test-1] Ready to get new events and compute a new plan
  2020-07-17 17:22:39,020 [INFO] [appgate-operator/appgate-test-1}] Event op: ADDED <class 'appgate.types.Condition'> with name my-new-condition
  2020-07-17 17:22:44,025 [INFO] [appgate-operator/appgate-test-1] No more events for a while, creating a plan
  2020-07-17 17:22:44,025 [WARNING] [appgate-operator/appgate-test-1] Running in dry-mode, nothing will be created
  2020-07-17 17:22:44,026 [INFO] [appgate-operator/appgate-test-1] AppgatePlan Summary:
  2020-07-17 17:22:44,026 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Condition'> Always [ee7b7e6f-e904-4b4f-a5ec-b3bef040643e]
  2020-07-17 17:22:44,026 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Condition'> my-new-condition [1bd1f4a8-d2ca-409d-b925-3530447caf45]
  2020-07-17 17:22:44,027 [INFO] [appgate-operator/appgate-test-1] = <class 'appgate.types.Policy'> Builtin Administrator Policy [172143a0-7ed4-11e4-b4a9-0800200c9a66]
#+END_EXAMPLE

**** TWO_WAY_SYNC
This flag makes the appgate-operator to read the current state from the
controller before computing the new plan. Basically whatever entity
created/deleted/modified manually will be reverted.

When it's not set it will just compute the plan against the current state in
memory (which could be different from the one in the controller).

*** Secrets
The operator supports 3 ways of dealing with secrets:
 - unencrypted secrets.
 - secrets encrypted with a [[https://cryptography.io/en/latest/fernet/][fernet]] key.
 - secrets saved as =secret= store in k8s.

**** Unencrypted secrets
In the first case (*unencrypted secrets*) we will save the secret in the yaml
file itself (or some tool will add it before pushing the event into k8s). In
this case the operator just uses that value as the value of the secrets field.

**** Encrypted secrets
We can also save an encrypted secret in the yaml file defining the entity, in
this case we need to provide a fermet key value in the environment variable
~APPGATE_OPERATOR_FERNET_KEY~ and the operator will decrypt the contents of the
value before using it.

In order to generate a new fernet key we can run:
#+begin_src shell
  python3 -c 'from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())'
#+end_src

In order to generate a secret with the new key we can do something like this:
#+begin_src shell
  SECRET='my-secret' KEY='dFVzzjKCa9mWbeig8dprliGLCXwnwE5Fbycz4Xe2ptk=' python3.9 -c 'from cryptography.fernet import Fernet;import os;print(Fernet(os.getenv("KEY")).encrypt(bytes(os.getenv("SECRET").encode())))'
#+end_src

Now it's safe to store the secrets in github.

If the variable ~APPGATE_OPERATOR_FERNET_KEY~ is set and the value of the secret
is a string then the operator will use the key to decrypt the secret.

**** k8s secret store
We can also use k8s the secrets store mechanism to save the secrets and reference
them in the yaml file. In this case we just set the value of the field with the
secret to a dictionary like this

#+begin_example
  type: k8s/secret
  password: my-secret
#+end_example

*** bytes
Some fields require bytes as a value (contents from a file for example) encoded
in base64. For now we only support the value encoded as base64 directly in the
yaml file.

** Building
The appgate-operator is provided as a docker image tagged with the appgate API
version. For example:

 - appgate-operator:v12
 - appgate-operator:v13
 - appgate-operator:v14
 - appgate-operator:v15
 - appgate-operator:v16

Each image uses that specific API version by default but contains the specs for
all the API versions supported.

To build the images we use a docker image as a builder with all the dependencies
needed.

In order to create the images run (~make docker-build-image is only needed if we
don't have yet the builder image or if we have changed any dependency):

#+BEGIN_SRC shell
  make docker-build-image && make docker-images
#+END_SRC

To push the images into a registry just run:

#+BEGIN_SRC shell
  for tag in v12 v13 v14 v15 v16; do
      docker tag appgate-operator:${tag} user/appgate-operator:${tag} && \
      docker push user/appgate-operator:${tag}
  done
#+END_SRC

** Configuration
The appgate-operator gets its configuration from environment variables (normally
specified in the pod yaml file).

Before deploying it MUST define these env variables:

 - APPGATE_OPERATOR_NAMESPACE :: the namespace the appgate-operator will watch
   events for.
 - APPGATE_OPERATOR_HOST :: the controller host the appgate-operator will be
   operating on.
 - APPGATE_OPERATOR_USER :: the user used to authenticate the REST calls to the
   controller.
 - APPGATE_OPERATOR_PASSWORD :: the password used to authenticate the REST calls
   to the controller.
 - APPGATE_OPERATOR_PROVIDER :: the provider used to authenticate the REST calls
   to the controller. The provider will default to local if not set.
 - APPGATE_OPERATOR_DEVICE_ID :: the device id used to authenticate the REST calls
   to the controller. The device id will be generated and stored in the operator's
   metadata configmap if not set. It will then be re-used in subsequent runs.

Optional environment variables that the operator uses:
 - APPGATE_OPERATOR_TIMEOUT :: Time without activity after which the appgate
   operator will try to apply changes received into a plan. Every time a new
   event is received this timer is reset to 0 again.
 - APPGATE_OPERATOR_DRY_RUN :: When set to 1 the operator will run in dry run
   mode. In this mode the operator will log all the actions but it won't perform
   any real action (delete, create or modify) in the conrtoller. Default value
   is 1.
 - APPGATE_OPERATOR_CLEANUP :: When set to 1 the operator will try to set the
   controller into the same state as the configuration. When set to 0 it won't
   try to delete the entities that are already defined in a controller. Default
   value is 1.
 - APPGATE_OPERATOR_TWO_WAY_SYNC :: When set to 1 it will read the current
   configuration from the controller just before computing the new plan. This
   basically means that whatever has been added / modified / deleted using the
   ui and not in the state represented in github will be discarded. Default
   value is 1.
 - APPGATE_OPERATOR_SPEC_DIRECTORY :: Directory where to look for the open api
   specification. By default each image version will default to a specific open
   api specification version. For example the image =appgate-operator:v12= will
   use *v12* as default open api specification version. This environment
   variable is normally not needed, if you want to use another version it's
   better to use the image created for that version instead..
 - APPGATE_OPERATOR_FERNET_KEY :: FERNET key used to encrypt secrets when this
   secrets mode is used.
 - APPGATE_OPERATOR_CONFIG_MAP :: k8s config-map used to store metadata related
   to entities used when comparing entitied with secrets. Default value is the
   ~APPGATE_OPERATOR_HOST~.
 - APPGATE_OPERATOR_SSL_NO_VERIFY :: When set to 1 the operator won't verify the
   validity of the SSL cerficate. Use this if you have a self signed
   certificate. Not recommended on production. Default value is 0.
 - APPGATE_OPERATOR_CACERT :: CA Certificate used by controllers (PEM
   format). It can be encoded in base64 or just the contents of the PEM
   certificate as a string, using the former makes it easier to add the
   certificate in k8s. Example:
 : export APPGATE_OPERATOR_CACERT=`cat cert.ca | base64 -w 0`
 : export APPGATE_OPERATOR_CACERT=`cat cert.ca`
 - APPGATE_OPERATOR_BUILTIN_TAGS :: List of tags (comma separated) defining
   builtin entities. Builtin entities are never deleted and when running in
   cleanup mode they are used to compute what entities should be
   deleted. Entities with tags belonging to this set are considered builtin
   entities.
 - APPGATE_OPERATOR_TARGET_TAGS :: List of tags (comma separated) defining the
   entities we are interested on. Only the entities in this set (entities with
   tags belonging to this set) will be selected from the appgate system. If no
   target tags are defined then all the entities will be selected.
 - APPGATE_OPERATOR_EXCLUDE_TAGS :: List of tags (comma separated) defining the
   set of entities we want to filter out explicitly from being
   selected. Entities with tags in this set will not be retrieved to compute the
   working plan.

*** Configuration when runinng the operator locally
In the case we run it locally for testing we only need to export those
environment variables before launching the process.

*** Configuration when running the operator incluster mode (inside k8s)
In this case the pod specification will get `APPGATE_OPERATOR_USER` and
`APPGATE_OPERATOR_PASSWORD` from a k8s Secret entry (see file
~manifests/01-secrets.yaml~).

The rest of environment variables are taken from a ConfigMap k8s entry (see
~manifests/01-config.yaml~).

** Testing locally against a k8s cluster
To test it follow these steps:

 - Create or get the =appgate-operator= image we want to use

 - Create a k8s cluster (and get the credentials)

 - Create some aliases
#+begin_src shell
  export API_VER=v13  # Use v12 to deploy for v12
  export APPGATE_NS=appgate-test
  export APPGATE_OPERATOR_PASSWORD='PASSWORD'
  export APPGATE_OPERATOR_USER='USER'
  export APPGATE_OPERATOR_HOST='https://controllerurl:444'
  alias appgate-operator="python3.9 -m appgate -l INFO"
  alias k="kubectl -n $APPGATE_NS"
  appgate-operator api-info  # This will show us info about the API we are gonna use
#+end_src

 - Create the namespace
#+BEGIN_SRC shell
  kubectl create namespace $APPGATE_NS
#+END_SRC

 - Create the CRDs
Now we will dump the CRD definition from the open api specficiation and we will
add it into the k8s cluster:
#+BEGIN_SRC shell
  appgate-operator dump-crd --spec-directory api_specs/${API_VER} --stdout > 00-appgate-test-crd-${API_VER}.yaml
  kubectl create -f 00-appgate-test-crd-v13.yaml
#+END_SRC

 - Create the configuration/secrets
We will create now the configuration needed to run the operator against our
appgate environment. We need to edit the files and set the values needed for our
environment. We will save
#+BEGIN_SRC shell
  k create -f manifests/01-config.yaml
  k create -f manifests/01-secrets.yaml
#+END_SRC

 - Add permissions to get/watch/list the CRD entities in appgate-operator
#+BEGIN_SRC shell
  k create -f manifests/01-role.yaml
#+END_SRC

 - Start the operator
#+BEGIN_SRC shell
  appgate-operator run --namespace $APPGATE_NS
#+END_SRC

 - Create the entities in k8s
#+BEGIN_SRC shell
  for example in examples/v13/*; do
      k create -f $example
  done
#+END_SRC

Now the operator should get the new events and reacto to them.

** Deploying the operator on a cluster
To deploy on a real k8s cluster follow these steps:

To deploy the operator inside the k8s cluster we need to follow almost the same
steps as before. The only difference is that now we will create a deployment for
the operator and it will run inside the cluster.

To achieve this replace the step where we were running the operator with this
command to create the deployment.

#+BEGIN_SRC shell
  k create -f manifests/02-appgate-operator.yaml
#+END_SRC

** Deploying the operator with argocd
In this setup we will use argocd to keep track of changes in a github repository
containing the desired state of the appgate environment.

We will use the push mode in argocd (someone or something needs to tell argocd
to sync when changes are done) but it's easy to change it to let argocd to pull
the repository to apply automatically changes (not recommended though).

*** Create cluster or use a cluster we already have.
The easies way of creating a cluster to start with is to use GCP. See GCP
documentation.

*** Install argocd in our cluster
This process is well explained in the argo web but let's summarized it:

#+BEGIN_SRC shell
  # Create a role binding allowing to user to do stuff
  kubectl create clusterrolebinding cluster-admin-binding \
      --clusterrole=cluster-admin --user="$(gcloud config get-value account)"

  # Create a new namespace to deploy the argocd stuff
  kubectl create namespace argocd

  # Install argocd in our cluster
  kubectl apply -n argocd \
      -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

  # Optional. Open the web ui to the exterior.
  kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
  ARGOCD_IP=$(kubectl get services -n argocd|awk '$2 ~ /LoadBalancer/ {print($4)}')

  # Get the password of our new argocd instace
  ARGOCD_PWD=$(kubectl get pods -n argocd|awk '$1 ~ /argocd-server/ {print($1)}')

  # Login into argocd
  argocd login $ARGOCD_IP

  # Change password, current password is in $ARGOCD_PWD
  argocd account update-password
#+END_SRC

*** Prepare appgate-operator
In this step we need to do basically the same we did when we configured the appgate for testing [[*Testing locally against a k8s cluster][locally]].
 - We will create first a new namespace in our cluster.
 - Then we will register the CRD data in k8s.
 - Finally we create the role allowing our pod to listen new events from the new
   CRD data.

#+BEGIN_SRC shell
  API_VER=v13  # Use v12 to deploy for v12
  APPGATE_NS=appgate-test
  alias k="kubectl -n ${APPGATE_NS}"
  alias appgate-operator="docker run --rm -v $HOME/.kube:/root/.kube appgate-operator:${API_VER}"
  kubectl create namespace ${APPGATE_NS}
  appgate-operator dump-crd -spec-directory api_specs/${API_VER} --stdout > 00-appgate-test-crd-${API_VER}.yaml
  kubectl create -f 00-appgate-test-crd-${API_VER}.yaml
  k create -f manifests/01-role.yaml
#+END_SRC

We need now to prepare the secrets in the namespace to be there ready for when
the deployment is done. If you have an automated way of dealing with secrets you
can omit this step.

The registry entry is only needed if we deploy the operator from a private
registry (we only have it in a private one right now). If it's coming from a
public one it's not needed and the deployment should be changed not to use the
credentials from here (see the k8s [[https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/][documentation]] for more details).

#+BEGIN_SRC shell
  # Only needed if you use a private docker repository
  kubectl create -f manifests/01-registry.yaml
  kubectl create -f manifests/01-secrets.yaml
#+END_SRC

*** Github preparations
Now we need to tell argocd about our application (the one containing all the
entities that we want to keep in sync via the appgate-operator).

In case your github repository is a private one you will need to do some extra
steps to make it available in gocd:

1. Create a new deployment key in the github's project.
2. Add the private part of the key in argocd (see argocd documentation).

*** Register the application in argocd
Now that we have everything ready we can create our new application in argocd.

Using the previous ssh key we added in argocd create a new application that
points to our repository in github and configure it to be deployed in the same
namespace we created when preparing the appgate-operator.

Set the sync mode to manual.

Once this is done we will see the new application appearing in the argocd web
ui. It says it's out of sync since we specified manual synchronization.

*** Environment preparations
At this point everything is ready to be executed but our environment needs to be
accessible from the nodes conforming the k8s cluster. Do whatever is needed in
your environment to make sure the k8s nodes can reach your controller for
instance in AWS we just need to add the public ip of the k8s nodes into the
security group used by the controller.

*** Syncing our application
Right now we have the application created in argocd pointing to the github
repository. That repository should contain a directory called ~appgate-test-1~
with the following files:

 - ~appgate-test-1/02-appgate-operator.yaml~ :: Deployment file.
 - ~appgate-test-1/01-config.yaml~ :: File with the configuration of
      appgate-operator.
 - ~appgate-test-1/entities.yaml~ :: File with the entities we want to have.

We don't need to have all the entities in one yaml file, we can have one file
per entity or one file per entity type, argocd will take care of syncing the CRD
objects created by the contents of those files.

Once all that is ready we can just press `sync` in the argocd web ui. If
everything works as expected argocd will create the new appgate-operator
deployment with the configuration and the entities specified.

*** Checking that it worked
We can see the logs of the pod created to run the appgate-operator in the argocd
web ui (we can see also the specs of all the objects synchronized).

If we prefer we can see the logs from the k8s cluster using `kubectl`:

#+BEGIN_SRC shell
  k get deployments # list the deployments
  k get pods # get all the pods, one of those is our appgate-operator
  k logs $(k get pods | awk '$3 ~ /Running/ {print($1)}') -f # see the logs
#+END_SRC

We can also see the current config and current secrets:
#+BEGIN_SRC shell
  k get config appgate-sdp-configmap -o yaml
  k get secret appgate-operator-secrets -o yaml
#+END_SRC

Or even the entities registered in the cluster (it should be the same as we have
in the git repository at this moment):

#+BEGIN_SRC shell
  k get policies
  k get entitlements
  k get conditions
#+END_SRC

*** Updating image
If we have a new image for the appgate-operator we want to deploy we can just
delete the current pod (using the argocd web ui or the kubectl command):

#+BEGIN_SRC shell
  k delete pod $(k get pods | awk '$3 ~ /Running/ {print($1)}')
  k logs $(k get pods | awk '$3 ~ /Running/ {print($1)}') -f
#+END_SRC

Since our operator runs as a deployment with replica 1, k8s will create a new
one pulling the new image from the docker registry.

*** Changing configuration manually
When synced for first time argocd will create the configmap with the
configuration used by the appgate-operator. It runs by default in dry-mode so it
would not do anything at this point (just printing the plan apply).

If we want to make it operate in normal mode we can just change the
configuration in the github repo, merge it and click sync again (the gitops
thing).

But we can also do it manually from argocd:

1. In the application view click the box representing the configmap.
2. There click edit and change the dry-run variable to "0"

At this point if you look into the configuration using kubectl you will see that
the value has changed:

#+BEGIN_SRC shell
  k get configmap appgate-sdp-configmap -o json|jq '.data["appgate-operator-dry-run"]'
#+END_SRC

Now we can just delete the pod again and a new one (using the new config) will
be deployed.

#+BEGIN_SRC shell
  k delete pod $(k get pods | awk '$3 ~ /Running/ {print($1)}')
#+END_SRC

*** Debugging
We can get the status of the operator like this:
#+BEGIN_SRC shell
  k describe appgate-operator
#+END_SRC

We can get the logs of the operator like this:
#+BEGIN_SRC shell
  k logs appgate-operator
#+END_SRC

** Dump current entities in an environment
To get the current entities from an existing environment we can call the
appgate-operator from the cli like this:

#+BEGIN_SRC shell
  appgate-operator dump-entities
#+END_SRC

That command will generate a new directory (with the current date as name)
containing all the entities discovered in the system:

#+BEGIN_EXAMPLE
  atuin ⊢ ls 2020-07-31
  administrativerole.yaml  appliance.yaml         condition.yaml        entitlement.yaml     identityprovider.yaml  localuser.yaml    policy.yaml         site.yaml
  adminmfasettings.yaml    clientconnection.yaml  criteriascripts.yaml  globalsettings.yaml  ippool.yaml            mfaprovider.yaml  ringfencerule.yaml
#+END_EXAMPLE

#+BEGIN_EXAMPLE
atuin ⊢ cat 2020-07-31/conditions.yaml
apiVersion: beta.appgate.com/v1
kind: CONDITION
metadata:
  name: my-new-condition
spec:
  expression: ' var result = false; /*password*/ if (claims.user.hasPassword(''test'',
    60)) { return true; } /*end password*/ return result; '
  id: 5283e6a7-7732-4260-a195-831f3e5ab6a5
  name: my-new-condition
  remedyMethods: []
  repeatSchedules:
  - '13:32'
  - 1h
  tags:
  - api-created
  - k8s
  - automated
---
apiVersion: beta.appgate.com/v1
kind: CONDITION
metadata:
  name: Always
spec:
  expression: return true;
  id: ee7b7e6f-e904-4b4f-a5ec-b3bef040643e
  name: Always
  notes: Condition for built-in usage.
  remedyMethods: []
  repeatSchedules: []
  tags:
  - builtin
---
#+END_EXAMPLE

** Verify entities dumped from an environment
If we have a set of entities dumped from an environment (like we did in the
previous step) we can validate them against different API version.

Suppose that we have a directory =exacmples/v13= with entities dumped from an
environment (running v13 of the API).

We can now test if those entities are compatible with different version.

Against the same api version (v13):

#+begin_example
  appgate-operator --spec-dir api_specs/v13 validate-entities examples/v13
#+end_example

That command will try to load all the entities defined in yaml files inside that
directory (*.yaml and *.yml files) using the API v13 and it will report errors
found when loading the entities:

#+begin_example
   - Appliance::controller-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
   - Appliance::gateway-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
   - DeviceScript::fooscript: OK.
   - TrustedCertificate::test-vsphere: OK.
   - EntitlementScript::hello: OK.
   - AdminMfaSettings::adminmfasettings: OK.
   - ClientConnection::clientconnection: OK.
   - LocalUser::bobbytables: OK.
   - Condition::always: OK.
   - IpPool::simple-setup-ipv6: OK.
   - IpPool::default-pool-v6: OK.
   - IpPool::simple-setup-ipv4: OK.
   - IpPool::default-pool-v4: OK.
   - IdentityProvider::connector: OK.
   - IdentityProvider::local: OK.
   - GlobalSettings::globalsettings: OK.
   - CriteriaScripts::everyone: OK.
   - CriteriaScripts::noone: OK.
   - RingfenceRule::block-in: OK.
   - RingfenceRule::block-google-dns: OK.
   - Policy::simple-setup-pol: OK.
   - Policy::builtin-administrator-policy: OK.
   - MfaProvider::default-fido2-provider: OK.
   - MfaProvider::default-time-based-otp-provider: OK.
   - MfaProvider::my-super-provider: OK.
   - ApplianceCustomization::params-adjustment: OK.
   - AdministrativeRole::system-administration: OK.
   - AdministrativeRole::api-access: OK.
   - Site::simple-setup-site: OK.
   - Site::default-site: OK.
   - Entitlement::simple-setup-ent-ping: OK.
   - Entitlement::simple-setup-ent-http: OK.
#+end_example

We can see that it managed to load those entities using v13. We can try the
same entities this time against v15 of the API:

#+begin_example
  appgate-operator --spec-dir api_specs/v15 validate-entities examples/v13
#+end_example

Once again we can see that they are compatible since we didn't get any error:

#+begin_example
   - Appliance::controller-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
   - Appliance::gateway-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
   - DeviceScript::fooscript: OK.
   - TrustedCertificate::test-vsphere: OK.
   - EntitlementScript::hello: OK.
   - AdminMfaSettings::adminmfasettings: OK.
   - ClientConnection::clientconnection: OK.
   - LocalUser::bobbytables: OK.
   - Condition::always: OK.
   - IpPool::simple-setup-ipv6: OK.
   - IpPool::default-pool-v6: OK.
   - IpPool::simple-setup-ipv4: OK.
   - IpPool::default-pool-v4: OK.
   - IdentityProvider::connector: OK.
   - IdentityProvider::local: OK.
   - GlobalSettings::globalsettings: OK.
   - CriteriaScripts::everyone: OK.
   - CriteriaScripts::noone: OK.
   - RingfenceRule::block-in: OK.
   - RingfenceRule::block-google-dns: OK.
   - Policy::simple-setup-pol: OK.
   - Policy::builtin-administrator-policy: OK.
   - MfaProvider::default-fido2-provider: OK.
   - MfaProvider::default-time-based-otp-provider: OK.
   - MfaProvider::my-super-provider: OK.
   - ApplianceCustomization::params-adjustment: OK.
   - AdministrativeRole::system-administration: OK.
   - AdministrativeRole::api-access: OK.
   - Site::simple-setup-site: OK.
   - Site::default-site: OK.
   - Entitlement::simple-setup-ent-ping: OK.
   - Entitlement::simple-setup-ent-http: OK.
#+end_example

Let's see what happens if we try to load them from an older version (like v12):

#+begin_example
  appgate-operator --spec-dir api_specs/v12 validate-entities examples/v13
#+end_example

This time the validator complains about some entities not being able to be
loaded (because API incompatibilities):

#+begin_example
   - Appliance::controller-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
   - Appliance::gateway-8b61286b-caf5-47df-8702-c1506a4afe3c-site1: OK.
   - DeviceScript::fooscript: OK.
   - TrustedCertificate::test-vsphere: OK.
   - EntitlementScript::hello: OK.
   - AdminMfaSettings::adminmfasettings: OK.
   - ClientConnection::clientconnection: OK.
   - LocalUser::bobbytables: OK.
   - Condition::always: OK.
   - IpPool::simple-setup-ipv6: OK.
   - IpPool::default-pool-v6: OK.
   - IpPool::simple-setup-ipv4: OK.
   - IpPool::default-pool-v4: OK.
   - IdentityProvider::connector: OK.
   - IdentityProvider::local: OK.
   - GlobalSettings::globalsettings: OK.
   - CriteriaScripts::everyone: OK.
   - CriteriaScripts::noone: OK.
   - RingfenceRule::block-in: ERROR: loading entity: loader: PlatformType.K8S, type: <class 'appgate.openapi.parser.RingfenceRule_Actions'>, value: [{'action': 'block', 'direction': 'in', 'hosts': ['0.0.0.0/0', '::0'], 'ports': ['1-65535'], 'protocol': 'tcp'}, {'action': 'block', 'direction': 'in', 'hosts': ['0.0.0.0/0', '::0'], 'ports': ['1-65535'], 'protocol': 'udp'}, {'action': 'block', 'direction': 'in', 'hosts': ['0.0.0.0/0'], 'protocol': 'icmp', 'types': ['0-255']}, {'action': 'block', 'direction': 'in', 'hosts': ['::0'], 'protocol': 'icmpv6', 'types': ['0-255']}].
   - RingfenceRule::block-google-dns: ERROR: loading entity: loader: PlatformType.K8S, type: <class 'appgate.openapi.parser.RingfenceRule_Actions'>, value: [{'action': 'allow', 'direction': 'out', 'hosts': ['8.8.8.8'], 'ports': ['53'], 'protocol': 'tcp'}].
   - Policy::simple-setup-pol: OK.
   - Policy::builtin-administrator-policy: OK.
   - MfaProvider::default-fido2-provider: OK.
   - MfaProvider::default-time-based-otp-provider: OK.
   - MfaProvider::my-super-provider: OK.
   - ApplianceCustomization::params-adjustment: OK.
   - AdministrativeRole::system-administration: OK.
   - AdministrativeRole::api-access: OK.
   - Site::simple-setup-site: OK.
   - Site::default-site: OK.
   - Entitlement::simple-setup-ent-ping: OK.
   - Entitlement::simple-setup-ent-http: OK.
#+end_example
