FROM python:3.9-slim
RUN apt-get update && \
    apt-get install make gcc libffi-dev --yes
COPY requirements-build.txt /build/
COPY requirements.txt /build/
RUN pip3 install -r /build/requirements-build.txt -r /build/requirements.txt
WORKDIR /build