{{- if not .Values.sdp.sdpOperator.configMapMt }}
{{- if has "sdp-operator" .Values.sdp.operators }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdp-operator.config-mt" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdp-operator.labels" . | nindent 4 }}
data:
{{- end }}
{{- end }}
