{{ if eq .Values.sdp.operator.mode "git-sync" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdp-operator.fullname" . }}-git-syncer
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdp-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sdp-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sdp-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.sdp.operator.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "sdp-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: APPGATE_OPERATOR_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: APPGATE_OPERATOR_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "sdp-operator.secret" . }}
                  key: appgate-operator-user
            - name: APPGATE_OPERATOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sdp-operator.secret" . }}
                  key: appgate-operator-password
            - name: APPGATE_OPERATOR_HOST
              value: {{ required "A valid .Values.sdp.operator.host entry is required!" .Values.sdp.operator.host }}
            - name: APPGATE_OPERATOR_DEVICE_ID
              value: {{ required "A valid .Values.sdp.operator.deviceId entry is required!" .Values.sdp.operator.deviceId }}
            - name: APPGATE_OPERATOR_LOG_LEVEL
              value: "{{ .Values.sdp.operator.logLevel }}"
            - name: APPGATE_OPERATOR_TIMEOUT
              value: "{{ .Values.sdp.operator.timeout }}"
            - name: APPGATE_OPERATOR_TARGET_TAGS
              value: "{{ join "," .Values.sdp.operator.targetTags }}"
            - name: APPGATE_OPERATOR_EXCLUDE_TAGS
              value: "{{ join "," .Values.sdp.operator.excludeTags }}"
            - name: APPGATE_OPERATOR_BUILTIN_TAGS
              value: "{{ join "," .Values.sdp.operator.builtinTags }}"
            - name: APPGATE_OPERATOR_CONFIG_MAP
              value: {{ default (include "sdp-operator.config-mt" .) .Values.sdp.operator.configMapMt }}
            {{- with .Values.sdp.operator.caCert }}
            - name: APPGATE_OPERATOR_CACERT
              value: "{{ . }}"
            {{- end }}
            {{- with .Values.sdp.operator.fernetKey }}
            - name: APPGATE_OPERATOR_FERNET_KEY
              value: "{{ . }}"
            {{- end }}
            {{- if eq .Values.sdp.operator.mode "git-sync" }}
            - name: GIT_VENDOR
              value: {{ .Values.sdp.operator.gitSync.git.vendor }}
            - name: GIT_REPOSITORY_URL
              value: {{ .Values.sdp.operator.gitSync.git.repositoryUrl }}
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sdp.operator.gitSync.git.secret }}
                  key: git-username
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sdp.operator.gitSync.git.secret }}
                  key: git-token
            - name: GIT_BASE_BRANCH
              value: {{ .Values.sdp.operator.gitSync.git.baseBranch }}
            {{- with .Values.sdp.operator.gitSync.github.repository }}
            - name: GITHUB_REPOSITORY
              value: {{ . }}
            {{- end }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sdp.operator.image.repository }}/sdp-operator:{{ default .Chart.AppVersion .Values.sdp.operator.image.tag}}"
          imagePullPolicy: {{ .Values.sdp.operator.image.pullPolicy }}
          command:
            - "/root/venv/bin/python3"
            - "-m"
            - "appgate.syncer"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{ end }}