{{- if has "sdp-operator" .Values.sdp.operators }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sdp-operator.serviceAccountName" .}}-sdp
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdp-operator.labels" . | nindent 4 }}
{{- end }}
---
{{- if has "git-operator" .Values.sdp.operators }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sdp-operator.serviceAccountName" .}}-git
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdp-operator.labels" . | nindent 4 }}
{{- end }}
