name: Build and Push Image

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        required: true

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install unzip

      - name: Download OpenAPI Spec
        shell: bash
        run: make clean && make api_specs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ inputs.push }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Operator App Version
        id: operatorAppVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.appVersion' k8s/operator/Chart.yaml

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-operator:${{ steps.operatorAppVersion.outputs.result }}
            ghcr.io/${{ github.repository }}/sdp-operator:latest
