name: Build and Push Image

on:
  workflow_run:
    workflow: [ "Build" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  build-push-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: openspecs
          path: /tmp
      - name: install unzip
        run: |
          sudo apt-get update
          sudo apt-get install unzip
      - name: Get Open API spec
        run: ./bin/unzip-open-spec.sh
        shell: bash
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Operator app version
        id: operatorAppVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.appVersion' k8s/operator/Chart.yaml
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}/sdp-operator:${{ steps.operatorAppVersion.outputs.result }}
