name: Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-push-image.yml
    with:
      push: true

  release-chart:
    uses: ./.github/workflows/release-chart.yml
    needs: build
    with:
      push: true

  releae-chart-oci:
    uses: ./.github/workflows/release-chart-oci.yml
    needs: build
    with:
      push: true
