name: Release Chart

on:
  workflow_call:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Appgate Cybersecurity"
          git config user.email "noreply@appgate.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: "k8s"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_OWNER: "appgate"
          CR_GIT_REPO: "sdp-operator"
          CR_CHARTS_DIR: "k8s"
          CR_SKIP_EXISTING: true
          CR_RELEASE_NAME_TEMPLATE: "v{{ .Version }}-{{ .Name }}"
          CR_GENERATE_RELEASE_NOTES: true
